name: Docker Logger Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create logs directory
      run: mkdir -p logs

    - name: Build Docker image
      run: docker build -t logger-app .

    - name: Run with test data
      run: |
        echo -e "GitHub Action Test Line 1\nTest Line 2\nFinal Line" | \
        docker run -i -v $(pwd)/logs:/home/logs logger-app
        
    - name: Show logs content
      run: |
        echo "--- Log file content ---"
        cat logs/log.txt
        echo "-----------------------"

    - name: Save logs as artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-logs
        path: logs/
        retention-days: 7

    - name: Generate test report
      run: |
        echo "## Test Results" >> report.md
        echo "- Build status: SUCCESS" >> report.md
        echo "- Log entries: $(wc -l < logs/log.txt)" >> report.md
        echo "### Log snippet" >> report.md
        echo '```' >> report.md
        head -n 3 logs/log.txt >> report.md
        echo '```' >> report.md
        echo "![Logs screenshot](https://github.com/${{ github.repository }}/actions/workflows/${{ github.workflow }}/badge.svg)" >> report.md

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: report.md
        retention-days: 7
